name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Initialise Airflow DB
      run: airflow db init
    - name: Test DAGs
      run: pytest --tb=short --disable-pytest-warnings --verbose
